automation: !include automations.yaml


command_line:
  - sensor:
      name: "KWL Temperatur nach Heizregister"
      unique_id: helios_t6_python_final_sensor
      command: "python3 /config/helios_modbus.py 192.168.1.199 8 v00146"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement
      value_template: >
        {% if '=' in value and 'v00146' in value %}
          {{ (value.split('=')[1] | replace(' ', '')) | float(20.0) }}
        {% else %}
          {% set alter_wert = states('sensor.kwl_temperatur_nach_heizregister') %}
          {{ alter_wert if alter_wert not in ['unknown', 'unavailable'] else 20.0 }}
        {% endif %}
      scan_interval: 30

shell_command:
  kwl_bypass_auto: "python3 /config/helios_modbus.py 192.168.1.199 8 v01035=23"
  kwl_bypass_auf: "python3 /config/helios_modbus.py 192.168.1.199 8 v01035=10"
  kwl_bypass_zu: "python3 /config/helios_modbus.py 192.168.1.199 8 v01035=40
